
services:
  mysql:
    image: mysql:8.0
    container_name: football_championship_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: football_championship
      MYSQL_USER: app
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
